name: cicd
on: push
env:
  NODE_VERSION: 16
jobs:
  test:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Test step
        run: echo Testing in Main...